version: "3.9"
services:
  qarzhy-tracker-server:
    build: .
    hostname: qarzhy-tracker-server
    environment:
      QARZHY_TRACKER_DATASOURCE_URL: ${QARZHY_TRACKER_DATASOURCE_URL}
      QARZHY_TRACKER_DATASOURCE_USERNAME: ${QARZHY_TRACKER_DATASOURCE_USERNAME}
      QARZHY_TRACKER_DATASOURCE_PASSWORD: ${QARZHY_TRACKER_DATASOURCE_PASSWORD}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      OPEN_AI_AUTHORIZATION_TOKEN: ${OPEN_AI_AUTHORIZATION_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - qarzhy-tracker-postgres

  qarzhy-tracker-postgres:
    image: postgres:15.2-alpine
    hostname: qarzhy-tracker-postgres
    environment:
      POSTGRES_DB: ${QARZHY_TRACKER_DB_NAME}
      POSTGRES_USER: ${QARZHY_TRACKER_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${QARZHY_TRACKER_DATASOURCE_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./data/app:/var/lib/postgresql/data"
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d transport-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  qarzhy-tracker-sonarqube-postgres:
    image: postgres:15.2-alpine
    hostname: qarzhy-tracker-postgres
    environment:
      POSTGRES_DB: ${QARZHY_TRACKER_SONARQUBE_DB_NAME}
      POSTGRES_USER: ${QARZHY_TRACKER_SONARQUBE_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${QARZHY_TRACKER_SONARQUBE_DATASOURCE_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5483:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d transport-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  qarzhy-tracker-sonarqube:
      image: sonarqube:lts-community
      depends_on:
        - qarzhy-tracker-sonarqube-postgres
      environment:
        SONAR_JDBC_URL: ${QARZHY_TRACKER_SONARQUBE_DATASOURCE_URL}
        SONAR_JDBC_USERNAME: ${QARZHY_TRACKER_SONARQUBE_DATASOURCE_USERNAME}
        SONAR_JDBC_PASSWORD: ${QARZHY_TRACKER_SONARQUBE_DATASOURCE_PASSWORD}
      ports:
        - "9001:9000"
      volumes:
        - "./sonarqube/conf:/opt/sonarqube/conf"
        - "./sonarqube/data:/opt/sonarqube/data"
        - "./sonarqube/extensions:/opt/sonarqube/extensions"
        - "./sonarqube/logs:/opt/sonarqube/logs"
        - "./sonarqube/temp:/opt/sonarqube/temp"
