spring:
  application:
    name: qarzhy-tracker
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/qarzhy_tracker_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:123456}
  flyway:
    enabled: true
  data:
    web:
      pageable:
        max-page-size: 50
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    token:
      expire-after: 30d

qarzhy-tracker:
  data:
    web:
      transaction-filter:
        date-format: 'yyy-MM-dd'
        search-parameter: search
        from-parameter: from
        to-parameter: to
        type-parameter: type
        from-days-offset: 7
