spring:
  application:
    name: qarzhy-tracker
  datasource:
    url: ${QARZHY_TRACKER_DATASOURCE_URL:jdbc:postgresql://localhost:5432/qarzhy_tracker_db}
    username: ${QARZHY_TRACKER_DATASOURCE_USERNAME:postgres}
    password: ${QARZHY_TRACKER_DATASOURCE_PASSWORD:123456}
  flyway:
    enabled: true
  data:
    web:
      pageable:
        max-page-size: 50
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    token:
      expire-after: 30d
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  cloud:
    openfeign:
      client:
        config:
          open-ai:
            url: ${qarzhy-tracker.open-ai.url}
            connectTimeout: 60000
            readTimeout: 60000

qarzhy-tracker:
  user-activation:
    delete-unverified-after: 30m
    verification:
      max-attempts: 3
      code-length: 6
      expire-after: 15m
  tokens:
    delete-expired-after: 1d
  data:
    web:
      transaction-filter:
        date-format: 'yyy-MM-dd'
        search-parameter: search
        from-parameter: from
        to-parameter: to
        type-parameter: type
        from-days-offset: 7
  open-ai:
    url: https://api.openai.com/v1/chat/completions
    token: ${OPEN_AI_AUTHORIZATION_TOKEN}
    default-settings:
      model: gpt-4o
      temperature: 1
      n: 1
      role: user
